Repository code-goodbuy/goodbuy-nodejs, pull requests merged in 2021-05, with the labels that each got.

#27 26 Add WatchTower to docker-compose
  Dockerfile
  docker-compose.local.yml
  docker-compose.test.yml
  docker-compose.yml
Labels: enhancement

#59 46 REST API crashes afters sending EAN code
  src/utils/send_ean.ts
Labels: bug

#65 Logging
  docker-compose.yml
  src/app.ts
Labels: backend
